name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        id: cacheNodeModules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        if: steps.cacheNodeModules.outputs.cahe-hit != 'true'
        run: |
          yarn install
        env:
          CI: true
      - name: test
        run: |
          yarn test
        env:
          CI: true
